// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/19/2025, 8:06:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/plugins/**/*.{js,ts,mjs}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/composables/**/*.{js,ts,mjs}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/utils/**/*.{js,ts,mjs}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/prakashranjanrai/Desktop/Accessibility-Analyzer-Tool/apps/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;